### select all

GET http://localhost:3000/albums HTTP/1.1

### eq

GET http://localhost:3000/albums?AlbumId=1 HTTP/1.1

### equals

GET http://localhost:3000/albums?AlbumId,eq=2 HTTP/1.1

### not equals

GET http://localhost:3000/albums?AlbumId,ne=2 HTTP/1.1

### in

GET http://localhost:3000/albums?AlbumId,in=1,2,3,4 HTTP/1.1

### not in

GET http://localhost:3000/albums?AlbumId,notin=1,2,3,4 HTTP/1.1


### greater/lesser than
GET http://localhost:3000/albums?AlbumId,gt=10&AlbumId,lt=20 HTTP/1.1

### greater/lesser equal
GET http://localhost:3000/albums?AlbumId,ge=10&AlbumId,le=20 HTTP/1.1

### like
GET http://localhost:3000/albums?Title,like=of HTTP/1.1

### not like
GET http://localhost:3000/albums?Title,notlike=of HTTP/1.1
